### ISSUE TITLE
TypeScript does not allow the css prop

### ISSUE THREAD

**Issue by mymphe** [lidofinance/ui#183]
There are times when you want to quickly change or override a css property and `styled-components`'s `css` function allows us to do it inline by passing the `css` prop, e.g.
```js
import { css } from 'styled-components';
// ...
<Input
  label="Amount"
  value={inputValue}
  css={css`background-color: red`}
/>
```
The biggest advantage of this approach over inline `style` prop is that we can use our global `theme` object.

However, currently the components' types do not support the `css` prop, as seen on the image below.
![image](https://user-images.githubusercontent.com/39704351/123218561-b2617080-d4ed-11eb-911a-01c80ca50afe.png)

**Comment by avsetsin** [comment]
This requires minor changes on the application side, but not the library
PR: https://github.com/lidofinance/lido-frontend-template/pull/2/files

More details:
https://styled-components.com/docs/api#usage-with-typescript
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245#issuecomment-446011384

@mymphe
