### ISSUE TITLE
Research: light/dark theme access by components for theme overrides

### ISSUE THREAD

**Issue by kolyasapphire** [lidofinance/ui#193]
We are currently unable to override theme for a single component.

This is useful in designs like this:
<img width="994" alt="Screenshot 2021-06-29 at 13 30 21" src="https://user-images.githubusercontent.com/4752441/123782591-2a5cdb80-d8de-11eb-95b7-2ddf11a04932.png">

**Comment by avsetsin** [comment]
This is a special block that does not change with the theme. And we already have a solution for it and components inside: `<Block color="accent" />` https://ui.lido.fi/?path=/story/layout-block--basic&args=color:accent
`<IdenticonBadge color="accent" />` https://ui.lido.fi/?path=/story/images-identicon--badge&args=color:accent

The same solution for Input (`<Input color="accent" />`): https://github.com/lidofinance/ui/pull/220

**Comment by kolyasapphire** [comment]
Yeah that's excellent, #220 fixes my troubles, thanks a lot!

But I was thinking to research a more high-level approach. We are heading to a position when we would probably need to implement deep theme switching logic into the lib itself. Eg persisting colour mode in localStorage, respecting browser's preferences and so on. We've got a lot of things to think through, might as well tackle this one (if receives support).

It would probably be handy to have something like a darkMode / lightMode boolean overriding prop on each component or a `<DarkMode></LightMode>` wrappers forcing a component to a fixed color theme.

**Comment by avsetsin** [comment]
Sounds useful. Re-opened the issue, I'll take a look
