### ISSUE TITLE
Toasts

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/ui#228]
We need a shared set of components, hooks or utils for "toasts". Current implementation based on `react-toastify`: https://github.com/lidofinance/lido-frontend-template/blob/main/components/toasts/

A few thoughts:
- Importing css doesn't seem like a very nice solution: https://github.com/lidofinance/lido-frontend-template/blob/main/components/toasts/toastContainer.tsx#L3 It would require an additional `styleInject` or something like that in the library. We're rewriting the styles anyway, it seems better to write all the styles with `styled components`.
- We can look at another solution instead of `react-toastify`. More compatible with our stack

**Comment by solidovic** [comment]
about first thought: i will use styled components theme.
second thought: i am bad at React libraries, but react-toastify has many stars and timely support releases, so i decided to use react-toastify.

**Comment by solidovic** [comment]
task should be closed
