### ISSUE TITLE
Modal elements

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/ui#230]
We could move the frequently used elements in modals to the library: 
- The button to connect to the wallets: https://www.figma.com/file/aXMwUrkMr2xT3pXhqaW8VG/Lido?node-id=7044%3A41046
- Load and success states: https://www.figma.com/file/aXMwUrkMr2xT3pXhqaW8VG/Lido?node-id=7044%3A43795

**Comment by Jds-23** [comment]
Hey, @avsetsin  , can you expand a bit? I am interested to work on it.

**Comment by avsetsin** [comment]
> Hey, @avsetsin , can you expand a bit? I am interested to work on it.

Hey! Thanks for your interest in the project. This is already implemented in #251. I will close the issue.
